### ISSUE TITLE
RandomCloze shows undefined instead of text

### ISSUE THREAD

**Issue by SlazZzor** [Vilhelm-Ian/Interactive_And_Randomize_Anki_Note_Types#14]
<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/7b2e3817-f8d7-4fb3-bed0-c19db84afb33" />
I run Anki app on MacOS Sequoia, Anki version 24.06.3

**Comment by SlazZzor** [comment]
Seems like the problem is here
```
const clozes = document.getElementById("hidden").innerHTML.split("|")
const rng = localStorage.getItem("rng")
document.getElementById("target").innerHTML = clozes[rng]
```
I don't really understand where does "rng" come from. When i check it with typeof it is an object not a number, that's why clozes[rng] gives undefined back. Is it supposed to work like that?

**Comment by SlazZzor** [comment]
If I understood correctly, the code difference between this git repository and anki addon website is huge. Is it a problem from my side or [Anki addon](https://ankiweb.net/shared/info/171015247) has the old out-of-date version?

**Comment by Vilhelm-Ian** [comment]
> If I understood correctly, the code difference between this git repository and anki addon website is huge. Is it a problem from my side or [Anki addon](https://ankiweb.net/shared/info/171015247) has the old out-of-date version?

I will update the code here

**Comment by Firewater21** [comment]
![Screenshot_2025-03-11-09-08-11-548_com.ichi2.anki.jpg](https://github.com/user-attachments/assets/a7559174-e76e-4cc6-85a2-fdd79919e854)

![Screenshot_2025-03-11-09-08-05-413_com.ichi2.anki.jpg](https://github.com/user-attachments/assets/84dd3d68-9057-4fb1-ab12-1fdd312e680c)

I observed the same when using Ankidroid.

**Comment by Vilhelm-Ian** [comment]
@Firewater21 I fixed it now

**Comment by Expertium** [comment]
Nope, still happens

![Image](https://github.com/user-attachments/assets/80ad4d38-d400-4f08-9213-e1c4084c849b)

![Image](https://github.com/user-attachments/assets/0629c5c7-45a3-4b6b-a8ac-f61068276c6c)

https://drive.google.com/file/d/1CTC2K1cHkhBBNbjuNaiVTviZACGZScoi/view?usp=sharing
